import pytest
import time

from IPA.app import create_app
from IPA.app.extensions import db
from IPA.app.models.mapping import Mapping
from IPA.app.services.mapping_service import update_mapping_table

# Generated by ChatGPT
@pytest.fixture(scope="function")
def test_db():
    """Fixture für die Flask-Testumgebung"""
    flask_app = create_app()
    flask_app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory:"  # In-Memory-DB

    with flask_app.app_context():
        db.create_all()  # Neue Tabellen für jeden Test
        update_mapping_table()
        yield flask_app  # Übergibt die Datenbank an den Test
        db.session.remove()
        db.drop_all()


def test_update_db_success(test_db):
    ''' testing if the mapping update acutally works '''
    Mapping.query.delete()
    db.session.commit()
    empty = Mapping.query.all()
    assert empty == []
    update_mapping_table()
    filled = Mapping.query.all()
    assert filled != []
    assert len(filled) > 10000